61/require loc
MunchApp/munch-server pull request #66
Opened 2019-11-15 04:17 UTC by kftang

2019-11-15 08:06 UTC, janinebar requested changes

2019-11-15 08:06 UTC, janinebar commented on routes/foodtrucks_test.go
> +	address := "1 direction st"
Nice

2019-11-15 08:06 UTC, janinebar commented on routes/foodtrucks_test.go
> +func TestFoodTruckPostInvalid(t *testing.T) {
Test single food truck or multiple food trucks? Look at func name and endpoint, make sure its clear

2019-11-15 08:06 UTC, janinebar commented on routes/foodtrucks_test.go
> +func TestFoodTruckPostUnauthorized(t *testing.T) {
Test single food truck or multiple food trucks? Look at func name and endpoint, make sure its clear

2019-11-15 23:08 UTC, kftang commented on routes/foodtrucks_test.go
> +func TestFoodTruckPostInvalid(t *testing.T) {
u rite

2019-11-15 23:09 UTC, kftang commented on routes/foodtrucks_test.go
> +func TestFoodTruckPostUnauthorized(t *testing.T) {
fixed

2019-11-16 00:59 UTC, janinebar approved these changes
tnx 4 da fix

2019-11-16 01:01 UTC, merged