Fixes #53
MunchApp/munch-server pull request #67
Opened 2019-11-15 04:48 UTC by kftang

2019-11-15 08:03 UTC, janinebar requested changes

2019-11-15 08:03 UTC, janinebar commented on routes/foodtrucks.go
> +	var foodTruck models.JSONFoodTruck
Just so i understand, but this is a check for if the food truck is in the db?

2019-11-15 08:03 UTC, janinebar commented on routes/foodtrucks_test.go
>  func TestFoodTruckGetInvalid(t *testing.T) {
Does endpoint match test goals (looking at func name)?

2019-11-15 08:03 UTC, janinebar commented on routes/foodtrucks_test.go
> +	req, _ := http.NewRequest("GET", "/foodtrucks", nil)
Here as well ^^^

2019-11-15 08:03 UTC, janinebar commented on routes/foodtrucks_test.go
> +	req, _ := http.NewRequest("GET", "/foodtrucks", nil)
Refer to above comment

2019-11-15 23:12 UTC, kftang commented on routes/foodtrucks.go
> +	var foodTruck models.JSONFoodTruck
yeah, just that

2019-11-15 23:13 UTC, kftang commented on routes/foodtrucks_test.go
> +	req, _ := http.NewRequest("GET", "/foodtrucks", nil)
yeah this is wrong

2019-11-15 23:13 UTC, kftang commented on routes/foodtrucks_test.go
> +	req, _ := http.NewRequest("GET", "/foodtrucks", nil)
it's ok because i still set the handler to the correct one (GetFoodTruckHandler) singular

2019-11-16 01:01 UTC, janinebar approved these changes

2019-11-16 02:25 UTC, merged