73/profile picture
MunchApp/munch-server pull request #77
Opened 2019-11-16 02:26 UTC by kftang

2019-11-16 03:26 UTC, janinebar requested changes

2019-11-16 03:26 UTC, janinebar commented on server.go
> +	sess, err := session.NewSession(&aws.Config{
handle error with log statement

2019-11-16 03:26 UTC, janinebar commented on routes/users.go
> +		w.WriteHeader(http.StatusInternalServerError)
add return in this error

2019-11-16 04:42 UTC, janinebar approved these changes

2019-11-20 02:54 UTC, kftang commented on routes/users.go
> +		Body:   file,
buffer, not file

2019-11-21 22:58 UTC, merged